sudo: 'required'

services:
  - 'docker'

before_install:
  - './.travis/main.sh'

script:
  - 'make test'
  - 'make image'

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ;
      make push-image ;
    fi

notifications:
  email: false

env:
  global:
    - "DOCKER_USERNAME=aidanns"
    - secure: "I7+iicoYYV2esgqU/KihlJgkp40g6tTMfxs9gaXLG3EF61eb6wXIAkFQ1sB6jDF8s8SnuINAodP6HJJgn4hi2p0gQS8Q31mCL+I3/Y7SjQceoy06MoLlUNU46e1IIRDOHOzL2iDhJunpbX2RO3gpPVt+IeC2N8XDUKZzAqovjIonf1BB9sRWa/9AMYMpFYYPv8+m8eM0RHypN5VdCkPGZHnnoldTCv1LpGmgGL0r0UOI12bmLztJBU1Grcl8v4eotIDVfwgZpwYtS+eDKgQu60mqbVF9BtnvpvDI0BkfGQSByStPgWtVf1mKLeROdNHIsrkyUut39xOmfu7b7dkTP0iGk5SqOJ4YnbqbsHNrmck2eKsSYIcW83lalvvGNdqxykySYbt8bYf9iyJ0WsM6XRDOtwuEqdQ06r97juOmpU75Dxm4PtXI52uHMNAx9rOtcIzeYaJsunx2QJ+M7MMHMIYvYq59jIYM0y8YXQyQtrqm0+8/sfxp0r4s03aU1vKTZrbb8yqJOTe4n/G1YQStJyzv19PDa9T38eTL1qRtlwShv4eM4YWockXXM5vvJebTRbPmT2gwJi2n7+it5lDSGV2KYC9B4FVgH7J8vEcmzhGYqRp7pqQzrZ58h0FJY7GXB7Twpg0nRKPlTbxxmt+0ol96Cq67T3CZeviee3lOOWk="
